name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        os: [ubuntu-latest]
        crystal:
          - 1.2.1
        include:
          - experimental: true
            os: ubuntu-latest
            crystal: nightly

    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.experimental }}

    container: crystallang/crystal:${{ matrix.crystal }}-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Run specs
        run: crystal spec -v --error-trace
